name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          glob_root_file: true
          args: "-pdf -jobname=./jaime_trovoada-resume -file-line-error -interaction=nonstopmode"
      - name: Build Zip
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: "*.pdf"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resume.pdf
            resume-chinese.pdf
